HIVE-4172 [jira] JDBC2 does not support VOID type
Summary:
HIVE-4172 JDBC2 does not support VOID type

In beeline, "select key, null from src" fails with exception,

org.apache.hive.service.cli.HiveSQLException: Error running query: java.lang.NullPointerException
	at org.apache.hive.service.cli.operation.SQLOperation.run(SQLOperation.java:112)
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatement(HiveSessionImpl.java:166)
	at org.apache.hive.service.cli.CLIService.executeStatement(CLIService.java:148)
	at org.apache.hive.service.cli.thrift.ThriftCLIService.ExecuteStatement(ThriftCLIService.java:183)
	at org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1133)
	at org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1118)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:39)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)

Test Plan: EMPTY

Reviewers: JIRA

Differential Revision: https://reviews.facebook.net/D9555