HIVE-3191 [jira] timestamp - timestamp causes null pointer exception
Summary:
DPAL-1389 Support arithmetic operations between timestamp types

select tts.rnum, tts.cts - tts.cts from cert.tts tts

Error: Query returned non-zero code: 12, cause: FAILED: Hive Internal Error: java.lang.NullPointerException(null)
SQLState:  42000
ErrorCode: 12

create table if not exists CERT.TTS ( RNUM int , CTS timestamp)
stored as sequencefile;

Test Plan: EMPTY

Reviewers: JIRA

Differential Revision: https://reviews.facebook.net/D3807