HIVE-4133 [jira] ClassNotFoundException for EventCounter in CDH3U1
Summary:
HIVE-4133 ClassNotFoundException for EventCounter in CDH3U1

Seemed regression from HIVE-3428

java.lang.RuntimeException: Could not load shims in class org.apache.hadoop.log.metrics.EventCounter
	at org.apache.hadoop.hive.shims.ShimLoader.createShim(ShimLoader.java:125)
	at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:117)
	at org.apache.hadoop.hive.shims.ShimLoader.getEventCounter(ShimLoader.java:100)
	at org.apache.hadoop.hive.shims.HiveEventCounter.<init>(HiveEventCounter.java:16)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at java.lang.Class.newInstance0(Class.java:355)
	at java.lang.Class.newInstance(Class.java:308)
	at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:330)
	at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:121)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:664)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:647)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:544)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:440)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:476)
	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:354)
	at org.apache.hadoop.hive.common.LogUtils.initHiveLog4jDefault(LogUtils.java:124)
	at org.apache.hadoop.hive.common.LogUtils.initHiveLog4jCommon(LogUtils.java:77)
	at org.apache.hadoop.hive.common.LogUtils.initHiveExecLog4j(LogUtils.java:69)
	at org.apache.hadoop.hive.ql.exec.ExecDriver.setupChildLog4j(ExecDriver.java:568)
	at org.apache.hadoop.hive.ql.exec.ExecDriver.main(ExecDriver.java:623)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:186)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.log.metrics.EventCounter
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:169)
	at org.apache.hadoop.hive.shims.ShimLoader.createShim(ShimLoader.java:122)
	... 27 more
log4j:ERROR Could not instantiate appender named "EventCounter".

Test Plan: EMPTY

Reviewers: JIRA

Differential Revision: https://reviews.facebook.net/D9195